[package]
name = "Downloader"
version = "1.0.0"
edition = "2021"
authors = ["Rayr"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
[dependencies]
reqwest = "0.11.7"
tokio = { version = "1", features = ["full"] }
